# Generated by Django 6.0.2 on 2026-02-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='is_uploaded',
            field=models.BooleanField(default=True),
        ),
    ]
